### ISSUE TITLE
notifications like approvals

### ISSUE THREAD

**Issue by patagoniahiker** [mrsalmon1976/Stateless.WorkflowEngine#14]
Hi, is there a simple notifications system like approval of documents and users or pub/sub

**Comment by mrsalmon1976** [comment]
Hi, I'm not sure what you mean?  This package just provides a framework for background workflows...notifications would be part of the implementation.  Or am I misunderstanding?

Cheers
Matt

**Comment by patagoniahiker** [comment]
Hi, thanks for the response, I was asking because I am trying to implement with your workflow.

The question is - can I notify target on workflow completion state.

**Comment by mrsalmon1976** [comment]
Hi

I have had the code for this sitting in a local branch for a while, and
I've been too lazy to push it out as I haven't had a personal need for it.

If you get the latest version of the code you have two options:

1. The WorkflowServer.WorkflowCompleted event - this can be raised on the
server whenever a workflow completes
2. workflow.OnCompleted() method - this can be overridden on your workflow
itself

Hope that helps,
Matt

**Comment by patagoniahiker** [comment]
That helps a good bit. Now can a user get notified like a _toaster_ event when he logs in. I.e. will it wait in queue and then be picked up/sent to the target person or group for e.g. on purchase/ document approved

**Comment by mrsalmon1976** [comment]
Hi

That sounds like the responsibility of the workflow you implement, not the
workflow engine itself.

Cheers
Matt

**Comment by mrsalmon1976** [comment]
The workflow engine is just a wrapper on a state machine.  It will handle
the movement from one state to the next, retry, and persistence to a data
store.

The actual workflow and movement between states is your responsibility, so
I think this may not be the tool for you.

It would probably help to read the Stateless documentation to understand
what this wrapper is really doing:

https://github.com/dotnet-state-machine/stateless

Cheers
Matt

**Comment by patagoniahiker** [comment]
ok thanks :+1:
