### ISSUE TITLE
Getting started sample code is missing

### ISSUE THREAD

**Issue by jorge-serrano** [mrsalmon1976/Stateless.WorkflowEngine#35]
I would like to have access to a sample code for implemented a basic workflow engine (like the bug tracker stateless sample) for get up to speed about using the package.
Sorry for putting this as an issue. It was the easiest way to communicate with you.

**Comment by mrsalmon1976** [comment]
Hi Jorge

This actually exists already - if you get the source and take a look in the folder:

Stateless.WorkflowEngine/source/Test.Stateless.WorkflowEngine.Example/

This contains an example of how you could create a windows service that uses the workflow engine to execute a simple workflow that generates files.

The example is pretty old, but it should give you a basic idea.

Is that what you're looking for?

Cheers
Matt

**Comment by jorge-serrano** [comment]
Thanks Matt.Yes, I can start with that. Only one additional question.. if I use parametrized steps in stateless, it will be compatible with the WF engine?I am trying to create a document approval workflow, so I will need to add extra info in some steps.
Regards, Jorge Serrano 

    On Thursday, April 11, 2019, 12:51:54 PM GMT-5, Matt Salmon <notifications@github.com> wrote:  
 
 
Hi Jorge

This actually exists already - if you get the source and take a look in the folder:

Stateless.WorkflowEngine/source/Test.Stateless.WorkflowEngine.Example/

This contains an example of how you could create a windows service that uses the workflow engine to execute a simple workflow that generates files.

The example is pretty old, but it should give you a basic idea.

Is that what you're looking for?

Cheers
Matt

**Comment by mrsalmon1976** [comment]
I'm not entirely sure what you mean, but the workflows run by the engine sit on top of stateless.  You can decorate your workflows with properties which will persist with the workflow itself and therefore be available throughout the life span of the workflow.  

When you define your workflow, you set up your states and triggers within the Initialise method, and the workflow class is just a wrapper over the StateMachine.  I think it should be compatible - if there's something you want added though, just let me know or create a pull request.

**Comment by jorge-serrano** [comment]
Thank you so much.
Regards, Jorge Serrano 

    On Thursday, April 11, 2019, 1:55:36 PM GMT-5, Matt Salmon <notifications@github.com> wrote:  
 
 
I'm not entirely sure what you mean, but the workflows run by the engine sit on top of stateless. You can decorate your workflows with properties which will persist with the workflow itself and therefore be available throughout the life span of the workflow.

When you define your workflow, you set up your states and triggers within the Initialise method, and the workflow class is just a wrapper over the StateMachine. I think it should be compatible - if there's something you want added though, just let me know or create a pull request.
